global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 0.5

  width: 2000.0
  height: 2000.0
  resolution: 0.025
  
  static_map: true
  origin_x: -4.0
  origin_y: -4.0

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    # - {name: laser_obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    # - {name: depth_obstacle_layer, type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}