local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0
  rolling_window: true
  
  width: 200.0
  height: 200.0
  resolution: 0.025

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}      
    # - {name: laser_obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: depth_obstacle_layer, type: "costmap_2d::VoxelLayer"}
    # - {name: head_stereo_obstacle_layer, type: "costmap_2d::VoxelLayer"}
    # - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
    # - {name: rs_st_obstacle_layer, type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
    # - {name: back_cam_obstacle_layer, type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}